GRD-106316 Adding the missing dependencies to build/lib
We keep seeing this issue on the UC packages created by UC Editor because of java.lang.NoClassDefFoundError: org/apache/commons/validator/routines/InetAddressValidato

Signed-off-by: Taees Eimouri <taees.eimouri1@ibm.com>